services:
  postgres:
    image: postgres:16-alpine
    container_name: skkolarship-postgres
    environment:
      POSTGRES_DB: skkolarship
      POSTGRES_USER: skkolarship
      POSTGRES_PASSWORD: skkolarship
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
